### ISSUE TITLE
Graphical designer for RapidScada

### ISSUE THREAD

**Issue by mdziczkowski** [RapidScada/scada#23] opened 2016-07-11 12:47 UTC
Please create a graphical editor for RapidScada with would work on Windows and Linux systems, with would allow to create own "interfaces" instead of having only the demo ones

**Comment by 2mik** [comment] 2016-07-11 12:53
Web editor is in the plans 2016.

**Comment by mcgiwer** [comment] 2016-07-11 15:16
@2mik Any idea when the works could start as soonest?

**Comment by 2mik** [comment] 2016-07-11 15:34
This is a major task. Do you have a deadline?
The schemes and tables editors will be developed as a web apps, but SCADA-Administrator and Server's and Communicator's shells still remain Windows desktop applications.

**Comment by mcgiwer** [comment] 2016-07-11 15:50
I don't have a deadline yet but I would like to earlier design and plan the whole instalation and it's controls before starting to implement it

**Comment by 2mik** [comment] 2016-07-11 17:14
I'd like not to promise an exact release date because it may be changed due to work load. The date can be fixed in case of commercial contract. Anyway you can use the current Windows GUI version of the editor while the new version is under construction.

**Comment by mcgiwer** [comment] 2016-07-11 23:16
> Anyway you can use the current Windows GUI version of the editor while the new version is under construction.

The problem is that I use Linux (Ubuntu) and there is not sure if it will run on iy

**Comment by 2mik** [comment] 2016-07-12 10:16
Porting all the apps to web requires huge LoE. As far as I know, you can use Windows emulator on Linux. Probably it is possible to launch GUI using Mono, but it requires a research. You can try to do it by yourself or we can discuss custom development if it is possible to pay for work.

**Closed** 2016-08-14 19:50 UTC
